### ISSUE TITLE
Tag a release?

### ISSUE THREAD

**Issue by REBELinBLUE** [melihovv/laravel-log-viewer#5]
Could you tag a new release for the laravel 5.5 support?

Thanks

**Comment by melihovv** [comment]
Latest release (5.5.0) has support for laravel 5.5. Check this travis build https://travis-ci.org/melihovv/laravel-log-viewer/builds/270061293

**Comment by REBELinBLUE** [comment]
Oh, weird. https://github.com/melihovv/laravel-log-viewer/releases shows 1.0.0 from January as the latest release, but I see it on the tags tab. Thanks
